### ISSUE TITLE
Configure travis to publish prerelease 

### ISSUE THREAD

**Issue by Deadarius** [conqa/serverless-openapi-documentation#12]
- travis deploy needs to be updated
- two deploy jobs - release @latest and release @next
- @latest (npm publish) should be released on tags matching only tags of format `v<Maj>.<Minor>.<Patch>`, such as`v1.0.0`
- @next ( npm publish --tag next)  should be released on tags matching only tags of format `v<Maj>.<Minor>.<Patch>-<Prerelease>`, such as`v1.0.0-alpha` or `v1.0.0-1`

Related travis documentation:
- https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

**Comment by orthanc** [comment]
This repo is not maintained
