### ISSUE TITLE
how to configure this plugin Documentation is not helping me

### ISSUE THREAD

**Issue by sandeep-datman** [conqa/serverless-openapi-documentation#27]
![image](https://user-images.githubusercontent.com/52954968/62824693-7b1a9c80-bbbf-11e9-922a-10fd3cff70d5.png)

**Comment by FreddyJD** [comment]
Wrap with " the import. yaml does not like the @

Example of my plugins:
```yml
plugins:
  - serverless-domain-manager 
  - serverless-mocha-plugin 
  - serverless-offline
  - "@conqa/serverless-openapi-documentation"
```

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
