### ISSUE TITLE
on generate api from yml to json, tags description and security per route not applying/showing on openapi.json 

### ISSUE THREAD

**Issue by 2arcz6** [conqa/serverless-openapi-documentation#29]
### My goal is to have these, inside openapi.json: 
<img width="824" alt="Screen Shot 2019-09-06 at 6 20 43 PM" src="https://user-images.githubusercontent.com/9163921/64492680-1d09d380-d2a9-11e9-9e52-d79eeab0e181.png">
<img width="653" alt="Screen Shot 2019-09-06 at 6 21 05 PM" src="https://user-images.githubusercontent.com/9163921/64492681-2135f100-d2a9-11e9-9272-1b628ac8d5cc.png">

### These is what I did on the yml file, but it is not updating the openapi.json:
<img width="897" alt="Screen Shot 2019-09-06 at 6 12 09 PM" src="https://user-images.githubusercontent.com/9163921/64492675-10857b00-d2a9-11e9-8e29-f645cd4b0c64.png">
<img width="957" alt="Screen Shot 2019-09-06 at 6 13 57 PM" src="https://user-images.githubusercontent.com/9163921/64492678-167b5c00-d2a9-11e9-9e99-f773e39b4a57.png">

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
