### ISSUE TITLE
Schema validation question.

### ISSUE THREAD

**Issue by FreddyJD** [conqa/serverless-openapi-documentation#32]
I cant thank enough every single collaborator in this fork. We started using serverless a few months ago and this was one of the last pieces of the puzzle.

My only concern is the schema-validation inside of AWS works with this package ? or do we still have to use _serverless-aws-documentation_ to validate everything ?  

Thanks.

**Comment by neftaly** [comment]
Hi! I'm glad you found use for it. We've had a bunch of arcane deployment systems at Conqa as serverless has become a thing, and wanted to standardize everything and push a rule that our systems must be self-describing and self-deploying. Unfortunately we're a little short-handed at the moment, so this fork isn't as supported as it could be. If you _or anyone reading this_ wants to take a look at getting CI working, I'll be happy to review and merge PRs going forward!

@wrumsby do you know if schema-validation works?

**Comment by neftaly** [comment]
Hi! I'm glad you found use for it. We've had a bunch of arcane deployment systems at Conqa as serverless has become a thing, and wanted to standardize everything and push a rule that our systems must be self-describing and self-deploying. Unfortunately we're a little short-handed at the moment, so this fork isn't as supported as it could be. If you or anyone reading this wants to take a look at getting CI working, I'd be happy to review and merge PRs to a community branch?

@wrumsby do you know if schema-validation works?

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
