### ISSUE TITLE
Add 'security' attribute for function 

### ISSUE THREAD

**Issue by romain-as** [conqa/serverless-openapi-documentation#33]
It would be nice to support the "security"  object at 'function' level. 
See 'Step 2. Applying security' at https://swagger.io/docs/specification/authentication/  

It's already managed in the 'custom' section, but will then apply to the whole API. Overloading at the function level would be useful.

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
