### ISSUE TITLE
Support for HttpApi

### ISSUE THREAD

**Issue by clarkd** [conqa/serverless-openapi-documentation#36]
This plugin doesn't seem to support HttpApi, i.e.

functions:
  list:
    handler: src/handler.list
    events:
      - **httpApi**:
          path: /subject
          method: GET
          documentation: ${file(documentation.yml):endpoints.list}

Just gets ignored when generating docs. Are there plans to support it?

**Comment by youngerjo** [comment]
I added a pull request #37

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
