### ISSUE TITLE
Type null not handle

### ISSUE THREAD

**Issue by VelikiiNehochuha** [conqa/serverless-openapi-documentation#38]
The schema with allow null not handled
`
{ "type":  ["string", "null"] }
`
According to [https://swagger.io/docs/specification/data-models/data-types/](https://swagger.io/docs/specification/data-models/data-types/)

null should be handled as property _nullabel: true_

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
