### ISSUE TITLE
Please update `swagger2openapi` to a version that doesn't pollute the global Object

### ISSUE THREAD

**Issue by vdh** [conqa/serverless-openapi-documentation#39]
The very old version of `swagger2openapi` uses `should` (ShouldJS) which mutates the global Object. Normally this is supposed to only be used in testing but this is being applied all the time.

Fixed here: https://github.com/Mermade/oas-kit/pull/83
and published in `swagger2openapi@3.2.9`

**Comment by orthanc** [comment]
Please note, this repository is UNMAINTAINED. It was a fork to fix a couple of issues but is no longer used by the maintainers. Feel free to create a maintained fork of this project to address any issues.
